### ISSUE TITLE
AdminConfigTestSettings 

### ISSUE THREAD

**Issue by ZeyangSun** [episerver/content-ab-testing#46]
Hi, I got the following errors after installing the package, how could it be resolved?

System.InvalidOperationException: No service for type 'EPiServer.Marketing.Testing.Web.Config.AdminConfigTestSettings' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at EPiServer.ServiceLocation.ServiceProviderExtensions.GetInstance[TService](IServiceProvider serviceProvider)
   at EPiServer.Marketing.Testing.Web.Jobs.TestSchedulingJob..ctor(IServiceProvider locator)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at EPiServer.Scheduler.Internal.DefaultScheduledJobFactory.Create(ScheduledJob job, IServiceProvider serviceProvider)
   at EPiServer.Scheduler.Internal.DefaultScheduledJobScanner.GetIsStoppable(ScheduledJob newScheduledJob)

**Comment by ZeyangSun** [comment]
Dulicated issue https://github.com/episerver/content-ab-testing/issues/46

**Comment by appendix68** [comment]
@ZeyangSun Did you found the solution?
